### ISSUE TITLE
Starship helm charts should depends only on promscale, timescaledb, and grafana

### ISSUE THREAD

**Issue by yaxiong-zhao** [tricorder-observability/helm-charts#100]
And make all other components optional.
Particularly depends directly on Grafana's helm-charts, disable the grafana of kube-prometheus-stack, and make kube-prometheus-stack completely optional

**Comment by JaredTan95** [comment]
revo

> {{- if or (and .Values.grafana.enabled .Values.grafana.defaultDashboardsEnabled) .Values.grafana.forceDeployDashboards }}

https://github.com/prometheus-community/helm-charts/blob/21ed9ed127a41802ddd7f4854d15467e78c84dc3/charts/kube-prometheus-stack/templates/grafana/configmap-dashboards.yaml#L1
