### ISSUE TITLE
Do not bundle the official OTel demo app's helm-charts in Starship helm-charts

### ISSUE THREAD

**Issue by yaxiong-zhao** [tricorder-observability/helm-charts#27]
RIght now we have demo app for prometheus, and open telemetry, which are all inside the tricorder namespace.

Especially the open telemetry demo app has more than 10 microservices.
Collectively, they put more pods in the tricorder namespace.

This makes it harder to find the relevant information, and increases the chance of mistakes.

**Comment by JaredTan95** [comment]
finished by https://github.com/tricorder-observability/helm-charts/pull/23
